name: FAIR Mappings Use Case submission
description: Use this template to submit a FAIR Mappings Use Case for the RDA FAIR Mappings Working Group. Please notice that we are looking for already implemented mapping use cases. 
title: FAIR Mappings Use Case submission
labels: [ use-case ]
assignees: jkesanie
body:
  - type: markdown
    attributes:
      value: |
        Some instructions for the submission.
  - type: input
    id: use-case-title
    attributes:
      label: The title of your use case
      description: A short but descriptive title that describes your use case.
    validations:
      required: true
  - type: input
    id: use-case-domain
    attributes:
      label: Domain
      description: Which scientific/activity domain do the mappings apply to?
    validations:
      required: true      
  - type: dropdown
    id: use-case-purpose-classified
    attributes:
      label: Purpose of the mapping
      description: Use this field as the primary way of selecting the purpose of your mappings. If the dropdown does not contain a suitable value, please add it throught the other option below. You can use both of the fields if dropdown options cover your case only partially.
      multiple: true
      options:
        - Semantic interoperability
        - Discovery
        - Data integration
    validations:
      required: false  
  - type: input
    id: use-case-purpose-string
    attributes:
      label: Other purpose of the mapping
      description: 
    validations:
      required: false       
  - type: textarea
    id: use-case-mapped-resources
    attributes:
      label: Type of mapped resources
      description: What kind of things are being mapped?
    validations:
      required: true      
  - type: textarea
    id: use-case-links
    attributes:
      label: Links to an existing mappings
      description: Links to resources that represent the actual mappings. Can be for example a service, api, code or a document. 
    validations:
      required: true
  - type: textarea
    id: use-case-tools
    attributes:
      label: Tools used for creating the mapping
    validations:
      required: true       
  - type: textarea
    id: use-case-mapping-relations
    attributes:
      label: Type of mapping relations
      description: e.g., unit conversion, synonymy, shared extension/referent, entity mappings, one to many, many to one
    validations:
      required: true
  - type: textarea
    id: use-case-implemenation-samples
    attributes:
      label: Examples (samples) of different types of mapping implementations 
      description: e.g. using pseudo-code, code-snippets, graph-based representation (nodes and edges), examples of source and target documents for transformations, …
    validations:
      required: true
